// Post-processes typedoc's Markdown output to add the YAML frontmatter
// Starlight requires (`title`, optional `description`). typedoc emits
// the page heading as the first H1; we lift that into frontmatter and
// strip the leading `# Heading` so Starlight's auto-rendering doesn't
// duplicate it.

import { readFileSync, writeFileSync, statSync } from "node:fs";
import { readdirSync } from "node:fs";
import { join, relative, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, "..", "src", "content", "docs", "api", "typescript");

function* walk(dir) {
    for (const entry of readdirSync(dir)) {
        const full = join(dir, entry);
        if (statSync(full).isDirectory()) yield* walk(full);
        else if (full.endsWith(".md")) yield full;
    }
}

let count = 0;
for (const file of walk(root)) {
    const original = readFileSync(file, "utf8");

    // Skip files that already have frontmatter — idempotent.
    if (original.startsWith("---\n")) continue;

    // Pull the first H1 as the title; fall back to the filename slug.
    const m = original.match(/^# +(.+?)\s*$/m);
    const title = (m?.[1] ?? relative(root, file).replace(/\.md$/, "").split(/[\/\\]/).join(" / "))
        .replace(/"/g, '\\"');

    // Strip the H1 line so Starlight doesn't double-render it.
    const body = m ? original.replace(/^# +.+?\s*$/m, "").replace(/^\n+/, "") : original;

    const frontmatter = `---\ntitle: "${title}"\n---\n\n`;
    writeFileSync(file, frontmatter + body, "utf8");
    count++;
}

console.log(`[post-typedoc] frontmatter applied to ${count} file(s)`);

// Write the umbrella index.md so /api/typescript/ renders as a Starlight
// page with linked cards into each typedoc module. typedoc clears its
// output dir on every run, so the umbrella has to be (re)created here.
const umbrella = `---
title: "TypeScript API"
description: "Generated reference for the AgentMux frontend public API surface."
---

Per-module reference for the TypeScript stores, reducers, and command source that make up the AgentMux frontend's public API. Generated by [typedoc](https://typedoc.org) from the pinned \`src/agentmux\` submodule.

## Modules

- [agent-document-store](./agent-document-store/readme/) — Document model + command/event types for the chat-style agent pane.
- [agent-pane-state-store](./agent-pane-state-store/readme/) — Pane registry, slot tracking, dispatch + snapshot helpers.
- [command-source](./command-source/readme/) — Command bus that pane-types subscribe to; source of UI-driven mutations.
- [launcher-event-reducer](./launcher-event-reducer/readme/) — Reducer over launcher events (process lifecycle, window reality).

## Cross-references

- [Rust API](/api/rust/) — rustdoc for the four crates in the Cargo workspace.
- [The reducer stack](/internals/reducer-stack/) — explains how these stores fit together.
- [Agent App API](/internals/agent-app-api/) — runtime API agents call to render their own UI.

## Regeneration

\`\`\`bash
npm run build:typedoc   # regenerates Markdown pages from the submodule's TypeScript source
npm run build:full      # build:typedoc + build:rust-docs + the Astro build
\`\`\`

The default \`npm run build\` deliberately skips typedoc so the docs site iterates without it. Production deploys must use \`build:full\`.
`;
writeFileSync(join(root, "index.md"), umbrella, "utf8");
console.log("[post-typedoc] wrote umbrella index.md");
